"""Initial schema: usuarios, tareas, importancia, estado, calificada

Revision ID: 06009f2cb2b5
Revises: 
Create Date: 2025-06-18 12:36:19.397531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06009f2cb2b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tareas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('completada', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.Date(), nullable=True),
    sa.Column('fecha_entrega', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('importancia_id', sa.String(length=2), nullable=True),
    sa.Column('estado_id', sa.String(length=2), nullable=True),
    sa.Column('asignado_a_id', sa.Integer(), nullable=True),
    sa.Column('calificacion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asignado_a_id'], ['usuarios.id'], name=op.f('fk_tareas_asignado_a_id_usuarios')),
    sa.ForeignKeyConstraint(['calificacion_id'], ['tb_tarea_calificada.cod_id_califica'], name=op.f('fk_tareas_calificacion_id_tb_tarea_calificada')),
    sa.ForeignKeyConstraint(['estado_id'], ['tb_estado_tarea.cod_id'], name=op.f('fk_tareas_estado_id_tb_estado_tarea')),
    sa.ForeignKeyConstraint(['importancia_id'], ['tb_importancia.cod_id'], name=op.f('fk_tareas_importancia_id_tb_importancia')),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], name=op.f('fk_tareas_user_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tareas'))
    )
    op.create_table('tb_estado_tarea',
    sa.Column('cod_id', sa.String(length=2), nullable=False),
    sa.Column('desc_estado_tarea', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('cod_id', name=op.f('pk_tb_estado_tarea'))
    )
    op.create_table('tb_importancia',
    sa.Column('cod_id', sa.String(length=2), nullable=False),
    sa.Column('tipo_importancia', sa.String(length=20), nullable=False),
    sa.Column('desc_importancia', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('cod_id', name=op.f('pk_tb_importancia'))
    )
    op.create_table('tb_tarea_calificada',
    sa.Column('cod_id_califica', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cod_id_tarea', sa.Integer(), nullable=False),
    sa.Column('fecha_calificado', sa.Date(), nullable=True),
    sa.Column('texto_calificado', sa.Text(), nullable=True),
    sa.Column('puntuacion_calificado', sa.Integer(), nullable=True),
    sa.Column('estatus_calificado', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['cod_id_tarea'], ['tareas.id'], name=op.f('fk_tb_tarea_calificada_cod_id_tarea_tareas')),
    sa.PrimaryKeyConstraint('cod_id_califica', name=op.f('pk_tb_tarea_calificada'))
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('clave_hash', sa.String(length=128), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('rol', sa.Enum('ADMIN', 'PROFESOR', 'ALUMNO', 'USER', name='rolenum'), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios')),
    sa.UniqueConstraint('email', name=op.f('uq_usuarios_email'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('tb_tarea_calificada')
    op.drop_table('tb_importancia')
    op.drop_table('tb_estado_tarea')
    op.drop_table('tareas')
    # ### end Alembic commands ###
