"""Agregar campos detalle_alumno y fecha_detalle_alumno a TareaCalificada

Revision ID: 35847497fc1c
Revises: 06009f2cb2b5
Create Date: 2025-06-19 13:57:29.176971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35847497fc1c'
down_revision = '06009f2cb2b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_tarea_calificada', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detalle_alumno', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('fecha_detalle_alumno', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_tarea_calificada', schema=None) as batch_op:
        batch_op.drop_column('fecha_detalle_alumno')
        batch_op.drop_column('detalle_alumno')

    # ### end Alembic commands ###
