"""Añade tablas Importancia, EstadoTarea, TareaCalificada + campos a Tarea

Revision ID: d96266364b8e
Revises: 2230a4161079
Create Date: 2025-06-17 14:09:43.664332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd96266364b8e'
down_revision = '2230a4161079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tareas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_entrega', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('importancia_id', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('estado_id', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('asignado_a_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('calificacion_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_tareas_asignado_a_id_usuarios'), 'usuarios', ['asignado_a_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_tareas_calificacion_id_tb_tarea_calificada'), 'tb_tarea_calificada', ['calificacion_id'], ['cod_id_califica'])
        batch_op.create_foreign_key(batch_op.f('fk_tareas_estado_id_tb_estado_tarea'), 'tb_estado_tarea', ['estado_id'], ['cod_id'])
        batch_op.create_foreign_key(batch_op.f('fk_tareas_importancia_id_tb_importancia'), 'tb_importancia', ['importancia_id'], ['cod_id'])

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_usuarios_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_usuarios_email'), type_='unique')

    with op.batch_alter_table('tareas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tareas_importancia_id_tb_importancia'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_tareas_estado_id_tb_estado_tarea'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_tareas_calificacion_id_tb_tarea_calificada'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_tareas_asignado_a_id_usuarios'), type_='foreignkey')
        batch_op.drop_column('calificacion_id')
        batch_op.drop_column('asignado_a_id')
        batch_op.drop_column('estado_id')
        batch_op.drop_column('importancia_id')
        batch_op.drop_column('fecha_entrega')

    # ### end Alembic commands ###
